services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_loan_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Password123
      - MSSQL_MEMORY_LIMIT_MB=1536
    ports:
      - "1433:1433"
    deploy:
      resources:
        limits:
          memory: 2G
    volumes:
      - sqlvolume:/var/opt/mssql

  backend:
    build:
      context: ./backend/src
      # Buscamos el Dockerfile dentro de la carpeta del proyecto espec√≠fico
      dockerfile: Fundo.Applications.WebApi/Dockerfile
    ports:
      - "5050:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=LoanDb;User Id=sa;Password=YourStrong@Password123;TrustServerCertificate=True;
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 512M

  frontend:
    build:
      # CAMBIO: Apuntamos directo a la carpeta 'frontend'
      context: ./frontend
      dockerfile: Dockerfile
    container_name: angular_app
    ports:
      - "4200:80"
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 128M

  seq:
    image: datalust/seq:latest
    container_name: seq-logs
    hostname: seq-server
    environment:
        - ACCEPT_EULA=Y
        - SEQ_FIRING_LINE_SIZE=1000
        - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
        - "5341:80"
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  sqlvolume:
